# Generated by Django 5.1.1 on 2024-11-10 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Course ID')),
                ('course_name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('tag_line', models.TextField(max_length=200, verbose_name='Tag Line')),
                ('description', models.TextField(max_length=2000, verbose_name='Description')),
                ('requirements', models.TextField(max_length=1000, verbose_name='Requirements')),
                ('duration', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Duration in Hrs')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='Creation Date')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/', verbose_name='Thumbnail')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('language', models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi'), ('AR', 'Arabic'), ('MR', 'Marathi'), ('FR', 'French'), ('ES', 'Spanish'), ('DE', 'German'), ('ZH', 'Chinese'), ('JA', 'Japanese'), ('KO', 'Korean'), ('PT', 'Portuguese'), ('IT', 'Italian'), ('RU', 'Russian'), ('TR', 'Turkish'), ('FA', 'Persian'), ('UR', 'Urdu'), ('BN', 'Bengali'), ('PA', 'Punjabi'), ('TA', 'Tamil'), ('TE', 'Telugu'), ('ML', 'Malayalam'), ('TH', 'Thai'), ('VI', 'Vietnamese'), ('ID', 'Indonesian'), ('EL', 'Greek'), ('SV', 'Swedish'), ('NL', 'Dutch'), ('HU', 'Hungarian'), ('PL', 'Polish'), ('HE', 'Hebrew'), ('CS', 'Czech'), ('RO', 'Romanian'), ('FI', 'Finnish'), ('NO', 'Norwegian'), ('UK', 'Ukrainian'), ('TL', 'Filipino'), ('MS', 'Malay'), ('SW', 'Swahili')], max_length=2, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Course Category ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Course Category Name')),
                ('description', models.TextField(max_length=500, verbose_name='Category Description')),
                ('image', models.ImageField(upload_to='category_images/', verbose_name='Category Image')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='User ID')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('age', models.IntegerField(verbose_name='Age')),
                ('gender', models.CharField(choices=[('N', 'Not disclose'), ('M', 'Male'), ('F', 'Female')], default='N', max_length=1, verbose_name='Gender')),
                ('phone', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Phone')),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], default='student', max_length=20, verbose_name='Role')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile pics/', verbose_name='Profile Picture')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('courses', models.ManyToManyField(related_name='enrolled_students', to='api.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='api.coursecategory'),
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Course Module ID')),
                ('module_name', models.CharField(max_length=200, verbose_name='Course Module Name')),
                ('description', models.TextField(max_length=500, verbose_name='Module Description')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Lecture ID')),
                ('lecture_name', models.CharField(max_length=100, verbose_name='Lecture Name')),
                ('video_link', models.URLField(blank=True, verbose_name='Lecture Video Link')),
                ('lecture_length', models.DurationField(verbose_name='Length of Lecture')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='api.coursemodule')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Document ID')),
                ('document_name', models.CharField(max_length=100, verbose_name='Document Name')),
                ('document_url', models.URLField(verbose_name='Document URL')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Review ID')),
                ('review_description', models.TextField(blank=True, null=True, verbose_name='Review Description')),
                ('given_rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, verbose_name='Star Rating')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('reviewer_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
