# Generated by Django 5.1.1 on 2024-11-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.CreateModel(
            name='CourseSubategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Course Subcategory ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Course Subcategory Name')),
                ('description', models.TextField(max_length=500, verbose_name='Category Description')),
                ('image', models.ImageField(upload_to='subcategory_images/', verbose_name='Subcategory Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coursecategory')),
            ],
        ),
    ]
