# Generated by Django 5.1.1 on 2024-11-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_reviews_review_coursesubategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseSubategory',
            new_name='CourseSubcategory',
        ),
    ]
