# Generated by Django 5.1.1 on 2024-11-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_coursesubategory_coursesubcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursesubcategory',
            old_name='category_name',
            new_name='subcategory_name',
        ),
    ]
