# Generated by Django 5.1.1 on 2024-11-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_category_name_coursesubcategory_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='subcategory_images/', verbose_name='Subcategory Image'),
        ),
    ]
