# Generated by Django 5.1.1 on 2024-11-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_coursesubcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_images/', verbose_name='Subcategory Image'),
        ),
    ]
