# Generated by Django 5.1.1 on 2024-11-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_course_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Creation Date'),
        ),
    ]
