# Generated by Django 5.1.1 on 2024-12-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='course_thumbnails/default-course.png', null=True, upload_to='course_thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
